services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: uv run python3 main.py
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    restart: always

volumes:
  mongo_data:
    driver: local
