services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    restart: always

  backend:
    image: telegram_miniapp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: uv run python3 main.py
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always

  worker:
    image: telegram_miniapp
    build:
        context: .
        dockerfile: Dockerfile
    container_name: worker
    command: uv run python3 -m worker
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    depends_on:
      - rabbit
      - backend
    restart: always

volumes:
  mongo_data:
    driver: local
  rabbit_data:
    driver: local